
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int parIzq = 17;
  public static final int parDer = 18;
  public static final int coma = 15;
  public static final int igualIgual = 13;
  public static final int menorIgual = 12;
  public static final int por = 8;
  public static final int llaveAbre = 19;
  public static final int menos = 7;
  public static final int llaveCierre = 20;
  public static final int EOF = 0;
  public static final int id = 22;
  public static final int error = 1;
  public static final int println_ = 5;
  public static final int if_ = 3;
  public static final int entero = 21;
  public static final int mayorIgual = 11;
  public static final int mas = 6;
  public static final int puntoComa = 16;
  public static final int menorQue = 10;
  public static final int int_ = 2;
  public static final int return_ = 4;
  public static final int and = 14;
  public static final int mayorQue = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "int_",
  "if_",
  "return_",
  "println_",
  "mas",
  "menos",
  "por",
  "mayorQue",
  "menorQue",
  "mayorIgual",
  "menorIgual",
  "igualIgual",
  "and",
  "coma",
  "puntoComa",
  "parIzq",
  "parDer",
  "llaveAbre",
  "llaveCierre",
  "entero",
  "id"
  };
}

